services:
  - type: web
    name: phish-detector
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 1 -b 0.0.0.0:10000"
    region: singapore
